# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/research_categories/research_categories.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3files/research_categories/research_categories.proto\x1a\x19\x66iles/common/common.proto\"\xb5\x07\n\x12ResearchCategories\x12\x41\n\x13research_categories\x18\x01 \x03(\x0b\x32$.ResearchCategories.ResearchCategory\x1am\n\x10ResearchCategory\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x36\n\x04info\x18\x02 \x01(\x0b\x32(.ResearchCategories.ResearchCategoryInfo\x1a\xec\x05\n\x14ResearchCategoryInfo\x12\x1d\n\x15\x65xpedition_reward_tag\x18\x01 \x01(\t\x12\"\n\x1a\x65xpedition_reward_type_tag\x18\x02 \x01(\t\x12\x15\n\runknown_1_int\x18\x03 \x01(\x05\x12\x18\n\x10\x65xpedition_image\x18\x04 \x01(\t\x12#\n\x1b\x65xpedition_name_placeholder\x18\x05 \x01(\t\x12,\n\x13\x65xpedition_category\x18\x06 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x18\n\x10name_placeholder\x18\x07 \x01(\t\x12\x1f\n\x17\x64\x65scription_placeholder\x18\x08 \x01(\t\x12\r\n\x05image\x18\t \x01(\t\x12\x15\n\runknown_2_int\x18\n \x01(\x05\x12\x15\n\rsort_priority\x18\x0b \x01(\x05\x12\x15\n\runknown_3_int\x18\x0c \x01(\x05\x12\x15\n\runknown_4_int\x18\r \x01(\x02\x12\x14\n\x0c\x62utton_image\x18\x0e \x01(\t\x12\x17\n\x0funknown_5_float\x18\x0f \x01(\x02\x12\x18\n\x10\x62\x61\x63kground_image\x18\x10 \x01(\t\x12\x1f\n\x17\x62\x61\x63kground_button_image\x18\x11 \x01(\t\x12\x0f\n\x07ripcord\x18\x12 \x01(\t\x12\'\n\x0e\x63\x61tegory_group\x18\x13 \x01(\x0b\x32\x0f.ObjectIdentity\x12\'\n\x0espeed_modifier\x18\x14 \x01(\x0b\x32\x0f.ObjectIdentity\x12H\n\tmodifiers\x18\x15 \x03(\x0b\x32\x35.ResearchCategories.ResearchCategoryInfo.CostModifier\x1aP\n\x0c\x43ostModifier\x12\x1d\n\x04item\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12!\n\x08modifier\x18\x02 \x01(\x0b\x32\x0f.ObjectIdentityb\x06proto3')



_RESEARCHCATEGORIES = DESCRIPTOR.message_types_by_name['ResearchCategories']
_RESEARCHCATEGORIES_RESEARCHCATEGORY = _RESEARCHCATEGORIES.nested_types_by_name['ResearchCategory']
_RESEARCHCATEGORIES_RESEARCHCATEGORYINFO = _RESEARCHCATEGORIES.nested_types_by_name['ResearchCategoryInfo']
_RESEARCHCATEGORIES_RESEARCHCATEGORYINFO_COSTMODIFIER = _RESEARCHCATEGORIES_RESEARCHCATEGORYINFO.nested_types_by_name['CostModifier']
ResearchCategories = _reflection.GeneratedProtocolMessageType('ResearchCategories', (_message.Message,), {

  'ResearchCategory' : _reflection.GeneratedProtocolMessageType('ResearchCategory', (_message.Message,), {
    'DESCRIPTOR' : _RESEARCHCATEGORIES_RESEARCHCATEGORY,
    '__module__' : 'files.research_categories.research_categories_pb2'
    # @@protoc_insertion_point(class_scope:ResearchCategories.ResearchCategory)
    })
  ,

  'ResearchCategoryInfo' : _reflection.GeneratedProtocolMessageType('ResearchCategoryInfo', (_message.Message,), {

    'CostModifier' : _reflection.GeneratedProtocolMessageType('CostModifier', (_message.Message,), {
      'DESCRIPTOR' : _RESEARCHCATEGORIES_RESEARCHCATEGORYINFO_COSTMODIFIER,
      '__module__' : 'files.research_categories.research_categories_pb2'
      # @@protoc_insertion_point(class_scope:ResearchCategories.ResearchCategoryInfo.CostModifier)
      })
    ,
    'DESCRIPTOR' : _RESEARCHCATEGORIES_RESEARCHCATEGORYINFO,
    '__module__' : 'files.research_categories.research_categories_pb2'
    # @@protoc_insertion_point(class_scope:ResearchCategories.ResearchCategoryInfo)
    })
  ,
  'DESCRIPTOR' : _RESEARCHCATEGORIES,
  '__module__' : 'files.research_categories.research_categories_pb2'
  # @@protoc_insertion_point(class_scope:ResearchCategories)
  })
_sym_db.RegisterMessage(ResearchCategories)
_sym_db.RegisterMessage(ResearchCategories.ResearchCategory)
_sym_db.RegisterMessage(ResearchCategories.ResearchCategoryInfo)
_sym_db.RegisterMessage(ResearchCategories.ResearchCategoryInfo.CostModifier)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESEARCHCATEGORIES._serialized_start=83
  _RESEARCHCATEGORIES._serialized_end=1032
  _RESEARCHCATEGORIES_RESEARCHCATEGORY._serialized_start=172
  _RESEARCHCATEGORIES_RESEARCHCATEGORY._serialized_end=281
  _RESEARCHCATEGORIES_RESEARCHCATEGORYINFO._serialized_start=284
  _RESEARCHCATEGORIES_RESEARCHCATEGORYINFO._serialized_end=1032
  _RESEARCHCATEGORIES_RESEARCHCATEGORYINFO_COSTMODIFIER._serialized_start=952
  _RESEARCHCATEGORIES_RESEARCHCATEGORYINFO_COSTMODIFIER._serialized_end=1032
# @@protoc_insertion_point(module_scope)
