# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/troops/troops.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66iles/troops/troops.proto\x1a\x19\x66iles/common/common.proto\"\xf4\x06\n\x06Troops\x12\x1d\n\x06troops\x18\x01 \x03(\x0b\x32\r.Troops.Troop\x1aK\n\x05Troop\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x1f\n\x04info\x18\x02 \x01(\x0b\x32\x11.Troops.TroopInfo\x1a\xb8\x05\n\tTroopInfo\x12\x18\n\x10name_placeholder\x18\x01 \x01(\t\x12\x1f\n\x17\x64\x65scription_placeholder\x18\x02 \x01(\t\x12\x12\n\nicon_image\x18\x03 \x01(\t\x12\x16\n\x0eportrait_image\x18\x04 \x01(\t\x12\x15\n\runknown_1_int\x18\x05 \x01(\x05\x12\x0c\n\x04tier\x18\x06 \x01(\x05\x12\r\n\x05power\x18\x08 \x01(\x01\x12\x0e\n\x06\x61ttack\x18\t \x01(\x05\x12\x13\n\x0bwall_damage\x18\n \x01(\x01\x12\x14\n\x0c\x61ttack_float\x18\x0b \x01(\x02\x12\x0f\n\x07\x64\x65\x66\x65nse\x18\x0c \x01(\x05\x12\x15\n\rdefense_float\x18\r \x01(\x02\x12\r\n\x05range\x18\x0e \x01(\x05\x12\x0e\n\x06health\x18\x0f \x01(\x05\x12\x14\n\x0chealth_float\x18\x10 \x01(\x02\x12\r\n\x05speed\x18\x11 \x01(\x05\x12\x12\n\ntroop_load\x18\x12 \x01(\x05\x12\x15\n\runknown_2_int\x18\x13 \x01(\x05\x12\x0e\n\x06upkeep\x18\x14 \x01(\x02\x12\x18\n\x10unknown_3_double\x18\x15 \x01(\x01\x12\x30\n\x0etraining_costs\x18\x18 \x03(\x0b\x32\x18.Troops.ItemWithQuantity\x12/\n\rhealing_costs\x18\x19 \x03(\x0b\x32\x18.Troops.ItemWithQuantity\x12\x33\n\x11resurecting_costs\x18\x1a \x03(\x0b\x32\x18.Troops.ItemWithQuantity\x12\x1f\n\x06traits\x18\x1b \x03(\x0b\x32\x0f.ObjectIdentity\x12\x17\n\x0funknown_4_float\x18\x1c \x01(\x02\x12\x14\n\x0cunlock_level\x18\x1d \x01(\x05\x12\x15\n\runknown_5_int\x18\x1e \x01(\x05\x12\x15\n\runknown_6_int\x18\x1f \x01(\x05\x1a\x43\n\x10ItemWithQuantity\x12\x1d\n\x04item\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x62\x06proto3')



_TROOPS = DESCRIPTOR.message_types_by_name['Troops']
_TROOPS_TROOP = _TROOPS.nested_types_by_name['Troop']
_TROOPS_TROOPINFO = _TROOPS.nested_types_by_name['TroopInfo']
_TROOPS_ITEMWITHQUANTITY = _TROOPS.nested_types_by_name['ItemWithQuantity']
Troops = _reflection.GeneratedProtocolMessageType('Troops', (_message.Message,), {

  'Troop' : _reflection.GeneratedProtocolMessageType('Troop', (_message.Message,), {
    'DESCRIPTOR' : _TROOPS_TROOP,
    '__module__' : 'files.troops.troops_pb2'
    # @@protoc_insertion_point(class_scope:Troops.Troop)
    })
  ,

  'TroopInfo' : _reflection.GeneratedProtocolMessageType('TroopInfo', (_message.Message,), {
    'DESCRIPTOR' : _TROOPS_TROOPINFO,
    '__module__' : 'files.troops.troops_pb2'
    # @@protoc_insertion_point(class_scope:Troops.TroopInfo)
    })
  ,

  'ItemWithQuantity' : _reflection.GeneratedProtocolMessageType('ItemWithQuantity', (_message.Message,), {
    'DESCRIPTOR' : _TROOPS_ITEMWITHQUANTITY,
    '__module__' : 'files.troops.troops_pb2'
    # @@protoc_insertion_point(class_scope:Troops.ItemWithQuantity)
    })
  ,
  'DESCRIPTOR' : _TROOPS,
  '__module__' : 'files.troops.troops_pb2'
  # @@protoc_insertion_point(class_scope:Troops)
  })
_sym_db.RegisterMessage(Troops)
_sym_db.RegisterMessage(Troops.Troop)
_sym_db.RegisterMessage(Troops.TroopInfo)
_sym_db.RegisterMessage(Troops.ItemWithQuantity)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TROOPS._serialized_start=57
  _TROOPS._serialized_end=941
  _TROOPS_TROOP._serialized_start=98
  _TROOPS_TROOP._serialized_end=173
  _TROOPS_TROOPINFO._serialized_start=176
  _TROOPS_TROOPINFO._serialized_end=872
  _TROOPS_ITEMWITHQUANTITY._serialized_start=874
  _TROOPS_ITEMWITHQUANTITY._serialized_end=941
# @@protoc_insertion_point(module_scope)
