# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/crafting_recipes/crafting_recipes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-files/crafting_recipes/crafting_recipes.proto\x1a\x19\x66iles/common/common.proto\"\xd0\x03\n\x0f\x43raftingRecipes\x12\x30\n\x07recipes\x18\x01 \x03(\x0b\x32\x1f.CraftingRecipes.CraftingRecipe\x1a\x66\n\x0e\x43raftingRecipe\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x31\n\x04info\x18\x02 \x01(\x0b\x32#.CraftingRecipes.CraftingRecipeInfo\x1a\xd6\x01\n\x12\x43raftingRecipeInfo\x12\x39\n\x0bingredients\x18\x03 \x03(\x0b\x32$.CraftingRecipes.CraftingIngredients\x12\x12\n\nsteel_cost\x18\x04 \x01(\x05\x12\x1c\n\x14upgrade_time_seconds\x18\x05 \x01(\x05\x12\x16\n\x0etemplate_level\x18\x06 \x01(\x05\x12$\n\x0b\x63raft_group\x18\x07 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x15\n\rsort_priority\x18\x08 \x01(\x05\x1aJ\n\x13\x43raftingIngredients\x12!\n\x08material\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x62\x06proto3')



_CRAFTINGRECIPES = DESCRIPTOR.message_types_by_name['CraftingRecipes']
_CRAFTINGRECIPES_CRAFTINGRECIPE = _CRAFTINGRECIPES.nested_types_by_name['CraftingRecipe']
_CRAFTINGRECIPES_CRAFTINGRECIPEINFO = _CRAFTINGRECIPES.nested_types_by_name['CraftingRecipeInfo']
_CRAFTINGRECIPES_CRAFTINGINGREDIENTS = _CRAFTINGRECIPES.nested_types_by_name['CraftingIngredients']
CraftingRecipes = _reflection.GeneratedProtocolMessageType('CraftingRecipes', (_message.Message,), {

  'CraftingRecipe' : _reflection.GeneratedProtocolMessageType('CraftingRecipe', (_message.Message,), {
    'DESCRIPTOR' : _CRAFTINGRECIPES_CRAFTINGRECIPE,
    '__module__' : 'files.crafting_recipes.crafting_recipes_pb2'
    # @@protoc_insertion_point(class_scope:CraftingRecipes.CraftingRecipe)
    })
  ,

  'CraftingRecipeInfo' : _reflection.GeneratedProtocolMessageType('CraftingRecipeInfo', (_message.Message,), {
    'DESCRIPTOR' : _CRAFTINGRECIPES_CRAFTINGRECIPEINFO,
    '__module__' : 'files.crafting_recipes.crafting_recipes_pb2'
    # @@protoc_insertion_point(class_scope:CraftingRecipes.CraftingRecipeInfo)
    })
  ,

  'CraftingIngredients' : _reflection.GeneratedProtocolMessageType('CraftingIngredients', (_message.Message,), {
    'DESCRIPTOR' : _CRAFTINGRECIPES_CRAFTINGINGREDIENTS,
    '__module__' : 'files.crafting_recipes.crafting_recipes_pb2'
    # @@protoc_insertion_point(class_scope:CraftingRecipes.CraftingIngredients)
    })
  ,
  'DESCRIPTOR' : _CRAFTINGRECIPES,
  '__module__' : 'files.crafting_recipes.crafting_recipes_pb2'
  # @@protoc_insertion_point(class_scope:CraftingRecipes)
  })
_sym_db.RegisterMessage(CraftingRecipes)
_sym_db.RegisterMessage(CraftingRecipes.CraftingRecipe)
_sym_db.RegisterMessage(CraftingRecipes.CraftingRecipeInfo)
_sym_db.RegisterMessage(CraftingRecipes.CraftingIngredients)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRAFTINGRECIPES._serialized_start=77
  _CRAFTINGRECIPES._serialized_end=541
  _CRAFTINGRECIPES_CRAFTINGRECIPE._serialized_start=146
  _CRAFTINGRECIPES_CRAFTINGRECIPE._serialized_end=248
  _CRAFTINGRECIPES_CRAFTINGRECIPEINFO._serialized_start=251
  _CRAFTINGRECIPES_CRAFTINGRECIPEINFO._serialized_end=465
  _CRAFTINGRECIPES_CRAFTINGINGREDIENTS._serialized_start=467
  _CRAFTINGRECIPES_CRAFTINGINGREDIENTS._serialized_end=541
# @@protoc_insertion_point(module_scope)
