# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/gear_stat_sets/gear_stat_sets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)files/gear_stat_sets/gear_stat_sets.proto\x1a\x19\x66iles/common/common.proto\"4\n\x0cGearStatSets\x12$\n\x0egear_stat_sets\x18\x01 \x03(\x0b\x32\x0c.GearStatSet\"\\\n\x0bGearStatSet\x12&\n\rgear_identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12%\n\x0egear_stat_list\x18\x02 \x01(\x0b\x32\r.GearStatList\"-\n\x0cGearStatList\x12\x1d\n\ngear_stats\x18\x01 \x03(\x0b\x32\t.GearStat\"S\n\x08GearStat\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12$\n\x0bprogression\x18\x02 \x01(\x0b\x32\x0f.ObjectIdentityb\x06proto3')



_GEARSTATSETS = DESCRIPTOR.message_types_by_name['GearStatSets']
_GEARSTATSET = DESCRIPTOR.message_types_by_name['GearStatSet']
_GEARSTATLIST = DESCRIPTOR.message_types_by_name['GearStatList']
_GEARSTAT = DESCRIPTOR.message_types_by_name['GearStat']
GearStatSets = _reflection.GeneratedProtocolMessageType('GearStatSets', (_message.Message,), {
  'DESCRIPTOR' : _GEARSTATSETS,
  '__module__' : 'files.gear_stat_sets.gear_stat_sets_pb2'
  # @@protoc_insertion_point(class_scope:GearStatSets)
  })
_sym_db.RegisterMessage(GearStatSets)

GearStatSet = _reflection.GeneratedProtocolMessageType('GearStatSet', (_message.Message,), {
  'DESCRIPTOR' : _GEARSTATSET,
  '__module__' : 'files.gear_stat_sets.gear_stat_sets_pb2'
  # @@protoc_insertion_point(class_scope:GearStatSet)
  })
_sym_db.RegisterMessage(GearStatSet)

GearStatList = _reflection.GeneratedProtocolMessageType('GearStatList', (_message.Message,), {
  'DESCRIPTOR' : _GEARSTATLIST,
  '__module__' : 'files.gear_stat_sets.gear_stat_sets_pb2'
  # @@protoc_insertion_point(class_scope:GearStatList)
  })
_sym_db.RegisterMessage(GearStatList)

GearStat = _reflection.GeneratedProtocolMessageType('GearStat', (_message.Message,), {
  'DESCRIPTOR' : _GEARSTAT,
  '__module__' : 'files.gear_stat_sets.gear_stat_sets_pb2'
  # @@protoc_insertion_point(class_scope:GearStat)
  })
_sym_db.RegisterMessage(GearStat)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEARSTATSETS._serialized_start=72
  _GEARSTATSETS._serialized_end=124
  _GEARSTATSET._serialized_start=126
  _GEARSTATSET._serialized_end=218
  _GEARSTATLIST._serialized_start=220
  _GEARSTATLIST._serialized_end=265
  _GEARSTAT._serialized_start=267
  _GEARSTAT._serialized_end=350
# @@protoc_insertion_point(module_scope)
