# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/hero_skills/hero_skills.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#files/hero_skills/hero_skills.proto\x1a\x19\x66iles/common/common.proto\"\xf8\x02\n\nHeroSkills\x12*\n\x0bhero_skills\x18\x01 \x03(\x0b\x32\x15.HeroSkills.HeroSkill\x1aW\n\tHeroSkill\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\'\n\x04info\x18\x02 \x01(\x0b\x32\x19.HeroSkills.HeroSkillInfo\x1at\n\rHeroSkillInfo\x12\x12\n\nskill_type\x18\x05 \x01(\t\x12\r\n\x05image\x18\x07 \x01(\t\x12*\n\x06values\x18\x08 \x03(\x0b\x32\x1a.HeroSkills.HeroSkillValue\x12\x14\n\x0cunlock_level\x18\t \x01(\x05\x1ao\n\x0eHeroSkillValue\x12\x1d\n\x04stat\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12$\n\x0bprogression\x18\x03 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x18\n\x10star_skill_value\x18\x04 \x01(\x01\x62\x06proto3')



_HEROSKILLS = DESCRIPTOR.message_types_by_name['HeroSkills']
_HEROSKILLS_HEROSKILL = _HEROSKILLS.nested_types_by_name['HeroSkill']
_HEROSKILLS_HEROSKILLINFO = _HEROSKILLS.nested_types_by_name['HeroSkillInfo']
_HEROSKILLS_HEROSKILLVALUE = _HEROSKILLS.nested_types_by_name['HeroSkillValue']
HeroSkills = _reflection.GeneratedProtocolMessageType('HeroSkills', (_message.Message,), {

  'HeroSkill' : _reflection.GeneratedProtocolMessageType('HeroSkill', (_message.Message,), {
    'DESCRIPTOR' : _HEROSKILLS_HEROSKILL,
    '__module__' : 'files.hero_skills.hero_skills_pb2'
    # @@protoc_insertion_point(class_scope:HeroSkills.HeroSkill)
    })
  ,

  'HeroSkillInfo' : _reflection.GeneratedProtocolMessageType('HeroSkillInfo', (_message.Message,), {
    'DESCRIPTOR' : _HEROSKILLS_HEROSKILLINFO,
    '__module__' : 'files.hero_skills.hero_skills_pb2'
    # @@protoc_insertion_point(class_scope:HeroSkills.HeroSkillInfo)
    })
  ,

  'HeroSkillValue' : _reflection.GeneratedProtocolMessageType('HeroSkillValue', (_message.Message,), {
    'DESCRIPTOR' : _HEROSKILLS_HEROSKILLVALUE,
    '__module__' : 'files.hero_skills.hero_skills_pb2'
    # @@protoc_insertion_point(class_scope:HeroSkills.HeroSkillValue)
    })
  ,
  'DESCRIPTOR' : _HEROSKILLS,
  '__module__' : 'files.hero_skills.hero_skills_pb2'
  # @@protoc_insertion_point(class_scope:HeroSkills)
  })
_sym_db.RegisterMessage(HeroSkills)
_sym_db.RegisterMessage(HeroSkills.HeroSkill)
_sym_db.RegisterMessage(HeroSkills.HeroSkillInfo)
_sym_db.RegisterMessage(HeroSkills.HeroSkillValue)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEROSKILLS._serialized_start=67
  _HEROSKILLS._serialized_end=443
  _HEROSKILLS_HEROSKILL._serialized_start=125
  _HEROSKILLS_HEROSKILL._serialized_end=212
  _HEROSKILLS_HEROSKILLINFO._serialized_start=214
  _HEROSKILLS_HEROSKILLINFO._serialized_end=330
  _HEROSKILLS_HEROSKILLVALUE._serialized_start=332
  _HEROSKILLS_HEROSKILLVALUE._serialized_end=443
# @@protoc_insertion_point(module_scope)
