# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/hero_skill_progressions/hero_skill_progressions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;files/hero_skill_progressions/hero_skill_progressions.proto\x1a\x19\x66iles/common/common.proto\"\xbf\x03\n\x15HeroSkillProgressions\x12L\n\x17hero_skill_progressions\x18\x01 \x03(\x0b\x32+.HeroSkillProgressions.HeroSkillProgression\x1aX\n\x14HeroSkillProgression\x12\n\n\x02id\x18\x01 \x01(\x06\x12\x34\n\x04info\x18\x02 \x01(\x0b\x32&.HeroSkillProgressions.ProgressionInfo\x1a\x7f\n\x0fProgressionInfo\x12\x32\n\tint_stats\x18\x01 \x01(\x0b\x32\x1f.HeroSkillProgressions.IntStats\x12\x38\n\x0c\x64ouble_stats\x18\x02 \x01(\x0b\x32\".HeroSkillProgressions.DoubleStats\x1a<\n\x08IntStats\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\r\n\x05stats\x18\x02 \x03(\x03\x1a?\n\x0b\x44oubleStats\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\r\n\x05stats\x18\x02 \x03(\x01\x62\x06proto3')



_HEROSKILLPROGRESSIONS = DESCRIPTOR.message_types_by_name['HeroSkillProgressions']
_HEROSKILLPROGRESSIONS_HEROSKILLPROGRESSION = _HEROSKILLPROGRESSIONS.nested_types_by_name['HeroSkillProgression']
_HEROSKILLPROGRESSIONS_PROGRESSIONINFO = _HEROSKILLPROGRESSIONS.nested_types_by_name['ProgressionInfo']
_HEROSKILLPROGRESSIONS_INTSTATS = _HEROSKILLPROGRESSIONS.nested_types_by_name['IntStats']
_HEROSKILLPROGRESSIONS_DOUBLESTATS = _HEROSKILLPROGRESSIONS.nested_types_by_name['DoubleStats']
HeroSkillProgressions = _reflection.GeneratedProtocolMessageType('HeroSkillProgressions', (_message.Message,), {

  'HeroSkillProgression' : _reflection.GeneratedProtocolMessageType('HeroSkillProgression', (_message.Message,), {
    'DESCRIPTOR' : _HEROSKILLPROGRESSIONS_HEROSKILLPROGRESSION,
    '__module__' : 'files.hero_skill_progressions.hero_skill_progressions_pb2'
    # @@protoc_insertion_point(class_scope:HeroSkillProgressions.HeroSkillProgression)
    })
  ,

  'ProgressionInfo' : _reflection.GeneratedProtocolMessageType('ProgressionInfo', (_message.Message,), {
    'DESCRIPTOR' : _HEROSKILLPROGRESSIONS_PROGRESSIONINFO,
    '__module__' : 'files.hero_skill_progressions.hero_skill_progressions_pb2'
    # @@protoc_insertion_point(class_scope:HeroSkillProgressions.ProgressionInfo)
    })
  ,

  'IntStats' : _reflection.GeneratedProtocolMessageType('IntStats', (_message.Message,), {
    'DESCRIPTOR' : _HEROSKILLPROGRESSIONS_INTSTATS,
    '__module__' : 'files.hero_skill_progressions.hero_skill_progressions_pb2'
    # @@protoc_insertion_point(class_scope:HeroSkillProgressions.IntStats)
    })
  ,

  'DoubleStats' : _reflection.GeneratedProtocolMessageType('DoubleStats', (_message.Message,), {
    'DESCRIPTOR' : _HEROSKILLPROGRESSIONS_DOUBLESTATS,
    '__module__' : 'files.hero_skill_progressions.hero_skill_progressions_pb2'
    # @@protoc_insertion_point(class_scope:HeroSkillProgressions.DoubleStats)
    })
  ,
  'DESCRIPTOR' : _HEROSKILLPROGRESSIONS,
  '__module__' : 'files.hero_skill_progressions.hero_skill_progressions_pb2'
  # @@protoc_insertion_point(class_scope:HeroSkillProgressions)
  })
_sym_db.RegisterMessage(HeroSkillProgressions)
_sym_db.RegisterMessage(HeroSkillProgressions.HeroSkillProgression)
_sym_db.RegisterMessage(HeroSkillProgressions.ProgressionInfo)
_sym_db.RegisterMessage(HeroSkillProgressions.IntStats)
_sym_db.RegisterMessage(HeroSkillProgressions.DoubleStats)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEROSKILLPROGRESSIONS._serialized_start=91
  _HEROSKILLPROGRESSIONS._serialized_end=538
  _HEROSKILLPROGRESSIONS_HEROSKILLPROGRESSION._serialized_start=194
  _HEROSKILLPROGRESSIONS_HEROSKILLPROGRESSION._serialized_end=282
  _HEROSKILLPROGRESSIONS_PROGRESSIONINFO._serialized_start=284
  _HEROSKILLPROGRESSIONS_PROGRESSIONINFO._serialized_end=411
  _HEROSKILLPROGRESSIONS_INTSTATS._serialized_start=413
  _HEROSKILLPROGRESSIONS_INTSTATS._serialized_end=473
  _HEROSKILLPROGRESSIONS_DOUBLESTATS._serialized_start=475
  _HEROSKILLPROGRESSIONS_DOUBLESTATS._serialized_end=538
# @@protoc_insertion_point(module_scope)
