# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/hero_collection_action_properties/hero_collection_action_properties.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nOfiles/hero_collection_action_properties/hero_collection_action_properties.proto\x1a\x19\x66iles/common/common.proto\"S\n\x1eHeroCollectionActionProperties\x12\x31\n\nproperties\x18\x01 \x03(\x0b\x32\x1d.HeroCollectionActionProperty\"\x90\x03\n\x1cHeroCollectionActionProperty\x12\n\n\x02id\x18\x01 \x01(\x06\x12\x38\n\x04info\x18\x02 \x01(\x0b\x32*.HeroCollectionActionProperty.PropertyInfo\x1a\x9e\x01\n\x0cPropertyInfo\x12G\n\x10integer_property\x18\x01 \x01(\x0b\x32-.HeroCollectionActionProperty.IntegerProperty\x12\x45\n\x0f\x64ouble_property\x18\x02 \x01(\x0b\x32,.HeroCollectionActionProperty.DoubleProperty\x1a\x44\n\x0fIntegerProperty\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x0e\n\x06values\x18\x02 \x03(\x03\x1a\x43\n\x0e\x44oubleProperty\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x0e\n\x06values\x18\x02 \x03(\x01\x62\x06proto3')



_HEROCOLLECTIONACTIONPROPERTIES = DESCRIPTOR.message_types_by_name['HeroCollectionActionProperties']
_HEROCOLLECTIONACTIONPROPERTY = DESCRIPTOR.message_types_by_name['HeroCollectionActionProperty']
_HEROCOLLECTIONACTIONPROPERTY_PROPERTYINFO = _HEROCOLLECTIONACTIONPROPERTY.nested_types_by_name['PropertyInfo']
_HEROCOLLECTIONACTIONPROPERTY_INTEGERPROPERTY = _HEROCOLLECTIONACTIONPROPERTY.nested_types_by_name['IntegerProperty']
_HEROCOLLECTIONACTIONPROPERTY_DOUBLEPROPERTY = _HEROCOLLECTIONACTIONPROPERTY.nested_types_by_name['DoubleProperty']
HeroCollectionActionProperties = _reflection.GeneratedProtocolMessageType('HeroCollectionActionProperties', (_message.Message,), {
  'DESCRIPTOR' : _HEROCOLLECTIONACTIONPROPERTIES,
  '__module__' : 'files.hero_collection_action_properties.hero_collection_action_properties_pb2'
  # @@protoc_insertion_point(class_scope:HeroCollectionActionProperties)
  })
_sym_db.RegisterMessage(HeroCollectionActionProperties)

HeroCollectionActionProperty = _reflection.GeneratedProtocolMessageType('HeroCollectionActionProperty', (_message.Message,), {

  'PropertyInfo' : _reflection.GeneratedProtocolMessageType('PropertyInfo', (_message.Message,), {
    'DESCRIPTOR' : _HEROCOLLECTIONACTIONPROPERTY_PROPERTYINFO,
    '__module__' : 'files.hero_collection_action_properties.hero_collection_action_properties_pb2'
    # @@protoc_insertion_point(class_scope:HeroCollectionActionProperty.PropertyInfo)
    })
  ,

  'IntegerProperty' : _reflection.GeneratedProtocolMessageType('IntegerProperty', (_message.Message,), {
    'DESCRIPTOR' : _HEROCOLLECTIONACTIONPROPERTY_INTEGERPROPERTY,
    '__module__' : 'files.hero_collection_action_properties.hero_collection_action_properties_pb2'
    # @@protoc_insertion_point(class_scope:HeroCollectionActionProperty.IntegerProperty)
    })
  ,

  'DoubleProperty' : _reflection.GeneratedProtocolMessageType('DoubleProperty', (_message.Message,), {
    'DESCRIPTOR' : _HEROCOLLECTIONACTIONPROPERTY_DOUBLEPROPERTY,
    '__module__' : 'files.hero_collection_action_properties.hero_collection_action_properties_pb2'
    # @@protoc_insertion_point(class_scope:HeroCollectionActionProperty.DoubleProperty)
    })
  ,
  'DESCRIPTOR' : _HEROCOLLECTIONACTIONPROPERTY,
  '__module__' : 'files.hero_collection_action_properties.hero_collection_action_properties_pb2'
  # @@protoc_insertion_point(class_scope:HeroCollectionActionProperty)
  })
_sym_db.RegisterMessage(HeroCollectionActionProperty)
_sym_db.RegisterMessage(HeroCollectionActionProperty.PropertyInfo)
_sym_db.RegisterMessage(HeroCollectionActionProperty.IntegerProperty)
_sym_db.RegisterMessage(HeroCollectionActionProperty.DoubleProperty)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEROCOLLECTIONACTIONPROPERTIES._serialized_start=110
  _HEROCOLLECTIONACTIONPROPERTIES._serialized_end=193
  _HEROCOLLECTIONACTIONPROPERTY._serialized_start=196
  _HEROCOLLECTIONACTIONPROPERTY._serialized_end=596
  _HEROCOLLECTIONACTIONPROPERTY_PROPERTYINFO._serialized_start=299
  _HEROCOLLECTIONACTIONPROPERTY_PROPERTYINFO._serialized_end=457
  _HEROCOLLECTIONACTIONPROPERTY_INTEGERPROPERTY._serialized_start=459
  _HEROCOLLECTIONACTIONPROPERTY_INTEGERPROPERTY._serialized_end=527
  _HEROCOLLECTIONACTIONPROPERTY_DOUBLEPROPERTY._serialized_start=529
  _HEROCOLLECTIONACTIONPROPERTY_DOUBLEPROPERTY._serialized_end=596
# @@protoc_insertion_point(module_scope)
