# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/recipe_display_groups/recipe_display_groups.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7files/recipe_display_groups/recipe_display_groups.proto\x1a\x19\x66iles/common/common.proto\"\xb8\x02\n\x13RecipeDisplayGroups\x12\x46\n\x15recipe_display_groups\x18\x01 \x03(\x0b\x32\'.RecipeDisplayGroups.RecipeDisplayGroup\x1ar\n\x12RecipeDisplayGroup\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x39\n\x04info\x18\x02 \x01(\x0b\x32+.RecipeDisplayGroups.RecipeDisplayGroupInfo\x1a\x65\n\x16RecipeDisplayGroupInfo\x12\x1a\n\x12\x64isplay_group_type\x18\x01 \x01(\t\x12\x18\n\x10name_placeholder\x18\x02 \x01(\t\x12\x15\n\rsort_priority\x18\x03 \x01(\x05\x62\x06proto3')



_RECIPEDISPLAYGROUPS = DESCRIPTOR.message_types_by_name['RecipeDisplayGroups']
_RECIPEDISPLAYGROUPS_RECIPEDISPLAYGROUP = _RECIPEDISPLAYGROUPS.nested_types_by_name['RecipeDisplayGroup']
_RECIPEDISPLAYGROUPS_RECIPEDISPLAYGROUPINFO = _RECIPEDISPLAYGROUPS.nested_types_by_name['RecipeDisplayGroupInfo']
RecipeDisplayGroups = _reflection.GeneratedProtocolMessageType('RecipeDisplayGroups', (_message.Message,), {

  'RecipeDisplayGroup' : _reflection.GeneratedProtocolMessageType('RecipeDisplayGroup', (_message.Message,), {
    'DESCRIPTOR' : _RECIPEDISPLAYGROUPS_RECIPEDISPLAYGROUP,
    '__module__' : 'files.recipe_display_groups.recipe_display_groups_pb2'
    # @@protoc_insertion_point(class_scope:RecipeDisplayGroups.RecipeDisplayGroup)
    })
  ,

  'RecipeDisplayGroupInfo' : _reflection.GeneratedProtocolMessageType('RecipeDisplayGroupInfo', (_message.Message,), {
    'DESCRIPTOR' : _RECIPEDISPLAYGROUPS_RECIPEDISPLAYGROUPINFO,
    '__module__' : 'files.recipe_display_groups.recipe_display_groups_pb2'
    # @@protoc_insertion_point(class_scope:RecipeDisplayGroups.RecipeDisplayGroupInfo)
    })
  ,
  'DESCRIPTOR' : _RECIPEDISPLAYGROUPS,
  '__module__' : 'files.recipe_display_groups.recipe_display_groups_pb2'
  # @@protoc_insertion_point(class_scope:RecipeDisplayGroups)
  })
_sym_db.RegisterMessage(RecipeDisplayGroups)
_sym_db.RegisterMessage(RecipeDisplayGroups.RecipeDisplayGroup)
_sym_db.RegisterMessage(RecipeDisplayGroups.RecipeDisplayGroupInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECIPEDISPLAYGROUPS._serialized_start=87
  _RECIPEDISPLAYGROUPS._serialized_end=399
  _RECIPEDISPLAYGROUPS_RECIPEDISPLAYGROUP._serialized_start=182
  _RECIPEDISPLAYGROUPS_RECIPEDISPLAYGROUP._serialized_end=296
  _RECIPEDISPLAYGROUPS_RECIPEDISPLAYGROUPINFO._serialized_start=298
  _RECIPEDISPLAYGROUPS_RECIPEDISPLAYGROUPINFO._serialized_end=399
# @@protoc_insertion_point(module_scope)
