# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/armory_stat_sets/armory_stat_sets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-files/armory_stat_sets/armory_stat_sets.proto\x1a\x19\x66iles/common/common.proto\":\n\x0e\x41rmoryStatSets\x12(\n\x10\x61rmory_stat_sets\x18\x01 \x03(\x0b\x32\x0e.ArmoryStatSet\"c\n\rArmoryStatSet\x12-\n\x14\x61rmory_stat_identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12#\n\x07wrapper\x18\x02 \x01(\x0b\x32\x12.ArmoryStatWrapper\"2\n\x11\x41rmoryStatWrapper\x12\x1d\n\x04info\x18\x01 \x01(\x0b\x32\x0f.ArmoryStatInfo\"Y\n\x0e\x41rmoryStatInfo\x12!\n\x08property\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12$\n\x0bprogression\x18\x02 \x01(\x0b\x32\x0f.ObjectIdentityb\x06proto3')



_ARMORYSTATSETS = DESCRIPTOR.message_types_by_name['ArmoryStatSets']
_ARMORYSTATSET = DESCRIPTOR.message_types_by_name['ArmoryStatSet']
_ARMORYSTATWRAPPER = DESCRIPTOR.message_types_by_name['ArmoryStatWrapper']
_ARMORYSTATINFO = DESCRIPTOR.message_types_by_name['ArmoryStatInfo']
ArmoryStatSets = _reflection.GeneratedProtocolMessageType('ArmoryStatSets', (_message.Message,), {
  'DESCRIPTOR' : _ARMORYSTATSETS,
  '__module__' : 'files.armory_stat_sets.armory_stat_sets_pb2'
  # @@protoc_insertion_point(class_scope:ArmoryStatSets)
  })
_sym_db.RegisterMessage(ArmoryStatSets)

ArmoryStatSet = _reflection.GeneratedProtocolMessageType('ArmoryStatSet', (_message.Message,), {
  'DESCRIPTOR' : _ARMORYSTATSET,
  '__module__' : 'files.armory_stat_sets.armory_stat_sets_pb2'
  # @@protoc_insertion_point(class_scope:ArmoryStatSet)
  })
_sym_db.RegisterMessage(ArmoryStatSet)

ArmoryStatWrapper = _reflection.GeneratedProtocolMessageType('ArmoryStatWrapper', (_message.Message,), {
  'DESCRIPTOR' : _ARMORYSTATWRAPPER,
  '__module__' : 'files.armory_stat_sets.armory_stat_sets_pb2'
  # @@protoc_insertion_point(class_scope:ArmoryStatWrapper)
  })
_sym_db.RegisterMessage(ArmoryStatWrapper)

ArmoryStatInfo = _reflection.GeneratedProtocolMessageType('ArmoryStatInfo', (_message.Message,), {
  'DESCRIPTOR' : _ARMORYSTATINFO,
  '__module__' : 'files.armory_stat_sets.armory_stat_sets_pb2'
  # @@protoc_insertion_point(class_scope:ArmoryStatInfo)
  })
_sym_db.RegisterMessage(ArmoryStatInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ARMORYSTATSETS._serialized_start=76
  _ARMORYSTATSETS._serialized_end=134
  _ARMORYSTATSET._serialized_start=136
  _ARMORYSTATSET._serialized_end=235
  _ARMORYSTATWRAPPER._serialized_start=237
  _ARMORYSTATWRAPPER._serialized_end=287
  _ARMORYSTATINFO._serialized_start=289
  _ARMORYSTATINFO._serialized_end=378
# @@protoc_insertion_point(module_scope)
