# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/armory_collections/armory_collections.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1files/armory_collections/armory_collections.proto\x1a\x19\x66iles/common/common.proto\"\xb2\x03\n\x11\x41rmoryCollections\x12?\n\x12\x61rmory_collections\x18\x01 \x03(\x0b\x32#.ArmoryCollections.ArmoryCollection\x1al\n\x10\x41rmoryCollection\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x35\n\x04info\x18\x02 \x01(\x0b\x32\'.ArmoryCollections.ArmoryCollectionInfo\x1a\x96\x01\n\x14\x41rmoryCollectionInfo\x12\x18\n\x10name_placeholder\x18\x03 \x01(\t\x12!\n\x08gear_set\x18\x04 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x10\n\x08priority\x18\x08 \x01(\x05\x12/\n\x07\x62onuses\x18\t \x03(\x0b\x32\x1e.ArmoryCollections.ArmoryBonus\x1aU\n\x0b\x41rmoryBonus\x12\x0f\n\x07quality\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12#\n\nbonus_info\x18\x03 \x01(\x0b\x32\x0f.ObjectIdentityb\x06proto3')



_ARMORYCOLLECTIONS = DESCRIPTOR.message_types_by_name['ArmoryCollections']
_ARMORYCOLLECTIONS_ARMORYCOLLECTION = _ARMORYCOLLECTIONS.nested_types_by_name['ArmoryCollection']
_ARMORYCOLLECTIONS_ARMORYCOLLECTIONINFO = _ARMORYCOLLECTIONS.nested_types_by_name['ArmoryCollectionInfo']
_ARMORYCOLLECTIONS_ARMORYBONUS = _ARMORYCOLLECTIONS.nested_types_by_name['ArmoryBonus']
ArmoryCollections = _reflection.GeneratedProtocolMessageType('ArmoryCollections', (_message.Message,), {

  'ArmoryCollection' : _reflection.GeneratedProtocolMessageType('ArmoryCollection', (_message.Message,), {
    'DESCRIPTOR' : _ARMORYCOLLECTIONS_ARMORYCOLLECTION,
    '__module__' : 'files.armory_collections.armory_collections_pb2'
    # @@protoc_insertion_point(class_scope:ArmoryCollections.ArmoryCollection)
    })
  ,

  'ArmoryCollectionInfo' : _reflection.GeneratedProtocolMessageType('ArmoryCollectionInfo', (_message.Message,), {
    'DESCRIPTOR' : _ARMORYCOLLECTIONS_ARMORYCOLLECTIONINFO,
    '__module__' : 'files.armory_collections.armory_collections_pb2'
    # @@protoc_insertion_point(class_scope:ArmoryCollections.ArmoryCollectionInfo)
    })
  ,

  'ArmoryBonus' : _reflection.GeneratedProtocolMessageType('ArmoryBonus', (_message.Message,), {
    'DESCRIPTOR' : _ARMORYCOLLECTIONS_ARMORYBONUS,
    '__module__' : 'files.armory_collections.armory_collections_pb2'
    # @@protoc_insertion_point(class_scope:ArmoryCollections.ArmoryBonus)
    })
  ,
  'DESCRIPTOR' : _ARMORYCOLLECTIONS,
  '__module__' : 'files.armory_collections.armory_collections_pb2'
  # @@protoc_insertion_point(class_scope:ArmoryCollections)
  })
_sym_db.RegisterMessage(ArmoryCollections)
_sym_db.RegisterMessage(ArmoryCollections.ArmoryCollection)
_sym_db.RegisterMessage(ArmoryCollections.ArmoryCollectionInfo)
_sym_db.RegisterMessage(ArmoryCollections.ArmoryBonus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ARMORYCOLLECTIONS._serialized_start=81
  _ARMORYCOLLECTIONS._serialized_end=515
  _ARMORYCOLLECTIONS_ARMORYCOLLECTION._serialized_start=167
  _ARMORYCOLLECTIONS_ARMORYCOLLECTION._serialized_end=275
  _ARMORYCOLLECTIONS_ARMORYCOLLECTIONINFO._serialized_start=278
  _ARMORYCOLLECTIONS_ARMORYCOLLECTIONINFO._serialized_end=428
  _ARMORYCOLLECTIONS_ARMORYBONUS._serialized_start=430
  _ARMORYCOLLECTIONS_ARMORYBONUS._serialized_end=515
# @@protoc_insertion_point(module_scope)
