# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/building_progressions/building_progressions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7files/building_progressions/building_progressions.proto\x1a\x19\x66iles/common/common.proto\"H\n\x14\x42uildingProgressions\x12\x30\n\x15\x62uilding_progressions\x18\x01 \x03(\x0b\x32\x11.ValueProgressionb\x06proto3')



_BUILDINGPROGRESSIONS = DESCRIPTOR.message_types_by_name['BuildingProgressions']
BuildingProgressions = _reflection.GeneratedProtocolMessageType('BuildingProgressions', (_message.Message,), {
  'DESCRIPTOR' : _BUILDINGPROGRESSIONS,
  '__module__' : 'files.building_progressions.building_progressions_pb2'
  # @@protoc_insertion_point(class_scope:BuildingProgressions)
  })
_sym_db.RegisterMessage(BuildingProgressions)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUILDINGPROGRESSIONS._serialized_start=86
  _BUILDINGPROGRESSIONS._serialized_end=158
# @@protoc_insertion_point(module_scope)
