# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/gear_stat_progressions/gear_stat_progressions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9files/gear_stat_progressions/gear_stat_progressions.proto\x1a\x19\x66iles/common/common.proto\"\xb7\x03\n\x14GearStatProgressions\x12I\n\x16gear_stat_progressions\x18\x01 \x03(\x0b\x32).GearStatProgressions.GearStatProgression\x1aV\n\x13GearStatProgression\x12\n\n\x02id\x18\x01 \x01(\x06\x12\x33\n\x04info\x18\x02 \x01(\x0b\x32%.GearStatProgressions.ProgressionInfo\x1a}\n\x0fProgressionInfo\x12\x31\n\tint_stats\x18\x01 \x01(\x0b\x32\x1e.GearStatProgressions.IntStats\x12\x37\n\x0c\x64ouble_stats\x18\x02 \x01(\x0b\x32!.GearStatProgressions.DoubleStats\x1a<\n\x08IntStats\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\r\n\x05stats\x18\x02 \x03(\x03\x1a?\n\x0b\x44oubleStats\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\r\n\x05stats\x18\x02 \x03(\x01\x62\x06proto3')



_GEARSTATPROGRESSIONS = DESCRIPTOR.message_types_by_name['GearStatProgressions']
_GEARSTATPROGRESSIONS_GEARSTATPROGRESSION = _GEARSTATPROGRESSIONS.nested_types_by_name['GearStatProgression']
_GEARSTATPROGRESSIONS_PROGRESSIONINFO = _GEARSTATPROGRESSIONS.nested_types_by_name['ProgressionInfo']
_GEARSTATPROGRESSIONS_INTSTATS = _GEARSTATPROGRESSIONS.nested_types_by_name['IntStats']
_GEARSTATPROGRESSIONS_DOUBLESTATS = _GEARSTATPROGRESSIONS.nested_types_by_name['DoubleStats']
GearStatProgressions = _reflection.GeneratedProtocolMessageType('GearStatProgressions', (_message.Message,), {

  'GearStatProgression' : _reflection.GeneratedProtocolMessageType('GearStatProgression', (_message.Message,), {
    'DESCRIPTOR' : _GEARSTATPROGRESSIONS_GEARSTATPROGRESSION,
    '__module__' : 'files.gear_stat_progressions.gear_stat_progressions_pb2'
    # @@protoc_insertion_point(class_scope:GearStatProgressions.GearStatProgression)
    })
  ,

  'ProgressionInfo' : _reflection.GeneratedProtocolMessageType('ProgressionInfo', (_message.Message,), {
    'DESCRIPTOR' : _GEARSTATPROGRESSIONS_PROGRESSIONINFO,
    '__module__' : 'files.gear_stat_progressions.gear_stat_progressions_pb2'
    # @@protoc_insertion_point(class_scope:GearStatProgressions.ProgressionInfo)
    })
  ,

  'IntStats' : _reflection.GeneratedProtocolMessageType('IntStats', (_message.Message,), {
    'DESCRIPTOR' : _GEARSTATPROGRESSIONS_INTSTATS,
    '__module__' : 'files.gear_stat_progressions.gear_stat_progressions_pb2'
    # @@protoc_insertion_point(class_scope:GearStatProgressions.IntStats)
    })
  ,

  'DoubleStats' : _reflection.GeneratedProtocolMessageType('DoubleStats', (_message.Message,), {
    'DESCRIPTOR' : _GEARSTATPROGRESSIONS_DOUBLESTATS,
    '__module__' : 'files.gear_stat_progressions.gear_stat_progressions_pb2'
    # @@protoc_insertion_point(class_scope:GearStatProgressions.DoubleStats)
    })
  ,
  'DESCRIPTOR' : _GEARSTATPROGRESSIONS,
  '__module__' : 'files.gear_stat_progressions.gear_stat_progressions_pb2'
  # @@protoc_insertion_point(class_scope:GearStatProgressions)
  })
_sym_db.RegisterMessage(GearStatProgressions)
_sym_db.RegisterMessage(GearStatProgressions.GearStatProgression)
_sym_db.RegisterMessage(GearStatProgressions.ProgressionInfo)
_sym_db.RegisterMessage(GearStatProgressions.IntStats)
_sym_db.RegisterMessage(GearStatProgressions.DoubleStats)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEARSTATPROGRESSIONS._serialized_start=89
  _GEARSTATPROGRESSIONS._serialized_end=528
  _GEARSTATPROGRESSIONS_GEARSTATPROGRESSION._serialized_start=188
  _GEARSTATPROGRESSIONS_GEARSTATPROGRESSION._serialized_end=274
  _GEARSTATPROGRESSIONS_PROGRESSIONINFO._serialized_start=276
  _GEARSTATPROGRESSIONS_PROGRESSIONINFO._serialized_end=401
  _GEARSTATPROGRESSIONS_INTSTATS._serialized_start=403
  _GEARSTATPROGRESSIONS_INTSTATS._serialized_end=463
  _GEARSTATPROGRESSIONS_DOUBLESTATS._serialized_start=465
  _GEARSTATPROGRESSIONS_DOUBLESTATS._serialized_end=528
# @@protoc_insertion_point(module_scope)
