# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/summons/summons.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x66iles/summons/summons.proto\x1a\x19\x66iles/common/common.proto\"\x93\x02\n\x07Summons\x12 \n\x07summons\x18\x01 \x03(\x0b\x32\x0f.Summons.Summon\x1aN\n\x06Summon\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12!\n\x04info\x18\x02 \x01(\x0b\x32\x13.Summons.SummonInfo\x1a\x95\x01\n\nSummonInfo\x12\x18\n\x10name_placeholder\x18\x02 \x01(\t\x12\x1f\n\x17\x64\x65scription_placeholder\x18\x03 \x01(\t\x12!\n\x08\x63\x61tegory\x18\x08 \x01(\x0b\x32\x0f.ObjectIdentity\x12)\n\x10purchase_options\x18\t \x03(\x0b\x32\x0f.ObjectIdentityb\x06proto3')



_SUMMONS = DESCRIPTOR.message_types_by_name['Summons']
_SUMMONS_SUMMON = _SUMMONS.nested_types_by_name['Summon']
_SUMMONS_SUMMONINFO = _SUMMONS.nested_types_by_name['SummonInfo']
Summons = _reflection.GeneratedProtocolMessageType('Summons', (_message.Message,), {

  'Summon' : _reflection.GeneratedProtocolMessageType('Summon', (_message.Message,), {
    'DESCRIPTOR' : _SUMMONS_SUMMON,
    '__module__' : 'files.summons.summons_pb2'
    # @@protoc_insertion_point(class_scope:Summons.Summon)
    })
  ,

  'SummonInfo' : _reflection.GeneratedProtocolMessageType('SummonInfo', (_message.Message,), {
    'DESCRIPTOR' : _SUMMONS_SUMMONINFO,
    '__module__' : 'files.summons.summons_pb2'
    # @@protoc_insertion_point(class_scope:Summons.SummonInfo)
    })
  ,
  'DESCRIPTOR' : _SUMMONS,
  '__module__' : 'files.summons.summons_pb2'
  # @@protoc_insertion_point(class_scope:Summons)
  })
_sym_db.RegisterMessage(Summons)
_sym_db.RegisterMessage(Summons.Summon)
_sym_db.RegisterMessage(Summons.SummonInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMMONS._serialized_start=59
  _SUMMONS._serialized_end=334
  _SUMMONS_SUMMON._serialized_start=104
  _SUMMONS_SUMMON._serialized_end=182
  _SUMMONS_SUMMONINFO._serialized_start=185
  _SUMMONS_SUMMONINFO._serialized_end=334
# @@protoc_insertion_point(module_scope)
