# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/heroes/heroes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66iles/heroes/heroes.proto\x1a\x19\x66iles/common/common.proto\"\xb5\x04\n\x06Heroes\x12\x1c\n\x06heroes\x18\x01 \x03(\x0b\x32\x0c.Heroes.Hero\x1aI\n\x04Hero\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x1e\n\x04info\x18\x02 \x01(\x0b\x32\x10.Heroes.HeroInfo\x1a\xed\x02\n\x08HeroInfo\x12\'\n\x0exp_progression\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x30\n\x17\x65vent_score_progression\x18\x02 \x01(\x0b\x32\x0f.ObjectIdentity\x12*\n\x11power_progression\x18\x03 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x0f\n\x07ripcord\x18\x05 \x01(\t\x12\x18\n\x10name_placeholder\x18\x06 \x01(\t\x12\x1f\n\x17\x64\x65scription_placeholder\x18\x07 \x01(\t\x12\x0e\n\x06rarity\x18\x08 \x01(\x05\x12\x11\n\tmax_stars\x18\t \x01(\x05\x12)\n\x0crequirements\x18\x13 \x03(\x0b\x32\x13.Heroes.Requirement\x12\x1f\n\x06skills\x18\x14 \x03(\x0b\x32\x0f.ObjectIdentity\x12\x1f\n\x06traits\x18\x15 \x03(\x0b\x32\x0f.ObjectIdentity\x1aR\n\x0bRequirement\x12\x1d\n\x04item\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12$\n\x0bprogression\x18\x02 \x01(\x0b\x32\x0f.ObjectIdentityb\x06proto3')



_HEROES = DESCRIPTOR.message_types_by_name['Heroes']
_HEROES_HERO = _HEROES.nested_types_by_name['Hero']
_HEROES_HEROINFO = _HEROES.nested_types_by_name['HeroInfo']
_HEROES_REQUIREMENT = _HEROES.nested_types_by_name['Requirement']
Heroes = _reflection.GeneratedProtocolMessageType('Heroes', (_message.Message,), {

  'Hero' : _reflection.GeneratedProtocolMessageType('Hero', (_message.Message,), {
    'DESCRIPTOR' : _HEROES_HERO,
    '__module__' : 'files.heroes.heroes_pb2'
    # @@protoc_insertion_point(class_scope:Heroes.Hero)
    })
  ,

  'HeroInfo' : _reflection.GeneratedProtocolMessageType('HeroInfo', (_message.Message,), {
    'DESCRIPTOR' : _HEROES_HEROINFO,
    '__module__' : 'files.heroes.heroes_pb2'
    # @@protoc_insertion_point(class_scope:Heroes.HeroInfo)
    })
  ,

  'Requirement' : _reflection.GeneratedProtocolMessageType('Requirement', (_message.Message,), {
    'DESCRIPTOR' : _HEROES_REQUIREMENT,
    '__module__' : 'files.heroes.heroes_pb2'
    # @@protoc_insertion_point(class_scope:Heroes.Requirement)
    })
  ,
  'DESCRIPTOR' : _HEROES,
  '__module__' : 'files.heroes.heroes_pb2'
  # @@protoc_insertion_point(class_scope:Heroes)
  })
_sym_db.RegisterMessage(Heroes)
_sym_db.RegisterMessage(Heroes.Hero)
_sym_db.RegisterMessage(Heroes.HeroInfo)
_sym_db.RegisterMessage(Heroes.Requirement)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEROES._serialized_start=57
  _HEROES._serialized_end=622
  _HEROES_HERO._serialized_start=97
  _HEROES_HERO._serialized_end=170
  _HEROES_HEROINFO._serialized_start=173
  _HEROES_HEROINFO._serialized_end=538
  _HEROES_REQUIREMENT._serialized_start=540
  _HEROES_REQUIREMENT._serialized_end=622
# @@protoc_insertion_point(module_scope)
