# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/hero_collection_actions/hero_collection_actions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;files/hero_collection_actions/hero_collection_actions.proto\x1a\x19\x66iles/common/common.proto\"\x80\x06\n\x15HeroCollectionActions\x12L\n\x17hero_collection_actions\x18\x01 \x03(\x0b\x32+.HeroCollectionActions.HeroCollectionAction\x1ax\n\x14HeroCollectionAction\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12=\n\x04info\x18\x02 \x01(\x0b\x32/.HeroCollectionActions.HeroCollectionActionInfo\x1a\xb9\x03\n\x18HeroCollectionActionInfo\x12\x18\n\x10name_placeholder\x18\x01 \x01(\t\x12\x1f\n\x17\x64\x65scription_placeholder\x18\x02 \x01(\t\x12\x12\n\nis_utility\x18\x03 \x01(\x05\x12\x17\n\x0funknown_1_int32\x18\x04 \x01(\x05\x12\r\n\x05image\x18\x05 \x01(\t\x12-\n\x14\x64uration_progression\x18\x06 \x01(\x0b\x32\x0f.ObjectIdentity\x12-\n\x14\x63ooldown_progression\x18\x07 \x01(\x0b\x32\x0f.ObjectIdentity\x12.\n\x15influence_progression\x18\x08 \x01(\x0b\x32\x0f.ObjectIdentity\x12*\n\x11level_progression\x18\t \x01(\x0b\x32\x0f.ObjectIdentity\x12-\n\x14num_uses_progression\x18\n \x01(\x0b\x32\x0f.ObjectIdentity\x12=\n\x04stat\x18\x0b \x01(\x0b\x32/.HeroCollectionActions.HeroCollectionActionStat\x1a\x63\n\x18HeroCollectionActionStat\x12!\n\x08property\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12$\n\x0bprogression\x18\x02 \x01(\x0b\x32\x0f.ObjectIdentityb\x06proto3')



_HEROCOLLECTIONACTIONS = DESCRIPTOR.message_types_by_name['HeroCollectionActions']
_HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTION = _HEROCOLLECTIONACTIONS.nested_types_by_name['HeroCollectionAction']
_HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTIONINFO = _HEROCOLLECTIONACTIONS.nested_types_by_name['HeroCollectionActionInfo']
_HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTIONSTAT = _HEROCOLLECTIONACTIONS.nested_types_by_name['HeroCollectionActionStat']
HeroCollectionActions = _reflection.GeneratedProtocolMessageType('HeroCollectionActions', (_message.Message,), {

  'HeroCollectionAction' : _reflection.GeneratedProtocolMessageType('HeroCollectionAction', (_message.Message,), {
    'DESCRIPTOR' : _HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTION,
    '__module__' : 'files.hero_collection_actions.hero_collection_actions_pb2'
    # @@protoc_insertion_point(class_scope:HeroCollectionActions.HeroCollectionAction)
    })
  ,

  'HeroCollectionActionInfo' : _reflection.GeneratedProtocolMessageType('HeroCollectionActionInfo', (_message.Message,), {
    'DESCRIPTOR' : _HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTIONINFO,
    '__module__' : 'files.hero_collection_actions.hero_collection_actions_pb2'
    # @@protoc_insertion_point(class_scope:HeroCollectionActions.HeroCollectionActionInfo)
    })
  ,

  'HeroCollectionActionStat' : _reflection.GeneratedProtocolMessageType('HeroCollectionActionStat', (_message.Message,), {
    'DESCRIPTOR' : _HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTIONSTAT,
    '__module__' : 'files.hero_collection_actions.hero_collection_actions_pb2'
    # @@protoc_insertion_point(class_scope:HeroCollectionActions.HeroCollectionActionStat)
    })
  ,
  'DESCRIPTOR' : _HEROCOLLECTIONACTIONS,
  '__module__' : 'files.hero_collection_actions.hero_collection_actions_pb2'
  # @@protoc_insertion_point(class_scope:HeroCollectionActions)
  })
_sym_db.RegisterMessage(HeroCollectionActions)
_sym_db.RegisterMessage(HeroCollectionActions.HeroCollectionAction)
_sym_db.RegisterMessage(HeroCollectionActions.HeroCollectionActionInfo)
_sym_db.RegisterMessage(HeroCollectionActions.HeroCollectionActionStat)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEROCOLLECTIONACTIONS._serialized_start=91
  _HEROCOLLECTIONACTIONS._serialized_end=859
  _HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTION._serialized_start=194
  _HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTION._serialized_end=314
  _HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTIONINFO._serialized_start=317
  _HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTIONINFO._serialized_end=758
  _HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTIONSTAT._serialized_start=760
  _HEROCOLLECTIONACTIONS_HEROCOLLECTIONACTIONSTAT._serialized_end=859
# @@protoc_insertion_point(module_scope)
