# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/summon_odds/summon_odds.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#files/summon_odds/summon_odds.proto\x1a\x19\x66iles/common/common.proto\"\xae\x02\n\x0fSummonOddsLists\x12:\n\x11summon_odds_lists\x18\x01 \x03(\x0b\x32\x1f.SummonOddsLists.SummonOddsList\x1a\\\n\x0eSummonOddsList\x12\x1b\n\x02id\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12-\n\x04info\x18\x02 \x01(\x0b\x32\x1f.SummonOddsLists.SummonOddsInfo\x1a\x80\x01\n\x0eSummonOddsInfo\x12(\n\x0fpurchase_option\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x1d\n\x04item\x18\x04 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x13\n\x0bprobability\x18\x06 \x01(\x02\x62\x06proto3')



_SUMMONODDSLISTS = DESCRIPTOR.message_types_by_name['SummonOddsLists']
_SUMMONODDSLISTS_SUMMONODDSLIST = _SUMMONODDSLISTS.nested_types_by_name['SummonOddsList']
_SUMMONODDSLISTS_SUMMONODDSINFO = _SUMMONODDSLISTS.nested_types_by_name['SummonOddsInfo']
SummonOddsLists = _reflection.GeneratedProtocolMessageType('SummonOddsLists', (_message.Message,), {

  'SummonOddsList' : _reflection.GeneratedProtocolMessageType('SummonOddsList', (_message.Message,), {
    'DESCRIPTOR' : _SUMMONODDSLISTS_SUMMONODDSLIST,
    '__module__' : 'files.summon_odds.summon_odds_pb2'
    # @@protoc_insertion_point(class_scope:SummonOddsLists.SummonOddsList)
    })
  ,

  'SummonOddsInfo' : _reflection.GeneratedProtocolMessageType('SummonOddsInfo', (_message.Message,), {
    'DESCRIPTOR' : _SUMMONODDSLISTS_SUMMONODDSINFO,
    '__module__' : 'files.summon_odds.summon_odds_pb2'
    # @@protoc_insertion_point(class_scope:SummonOddsLists.SummonOddsInfo)
    })
  ,
  'DESCRIPTOR' : _SUMMONODDSLISTS,
  '__module__' : 'files.summon_odds.summon_odds_pb2'
  # @@protoc_insertion_point(class_scope:SummonOddsLists)
  })
_sym_db.RegisterMessage(SummonOddsLists)
_sym_db.RegisterMessage(SummonOddsLists.SummonOddsList)
_sym_db.RegisterMessage(SummonOddsLists.SummonOddsInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMMONODDSLISTS._serialized_start=67
  _SUMMONODDSLISTS._serialized_end=369
  _SUMMONODDSLISTS_SUMMONODDSLIST._serialized_start=146
  _SUMMONODDSLISTS_SUMMONODDSLIST._serialized_end=238
  _SUMMONODDSLISTS_SUMMONODDSINFO._serialized_start=241
  _SUMMONODDSLISTS_SUMMONODDSINFO._serialized_end=369
# @@protoc_insertion_point(module_scope)
