# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/gear_sets/gear_sets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x66iles/gear_sets/gear_sets.proto\x1a\x19\x66iles/common/common.proto\"\'\n\x08GearSets\x12\x1b\n\tgear_sets\x18\x01 \x03(\x0b\x32\x08.GearSet\"H\n\x07GearSet\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x1a\n\x04info\x18\x02 \x01(\x0b\x32\x0c.GearSetInfo\"\xbd\x01\n\x0bGearSetInfo\x12\x18\n\x10name_placeholder\x18\x01 \x01(\t\x12\x1f\n\x17\x64\x65scription_placeholder\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\t\x12\x15\n\x05\x63olor\x18\x05 \x01(\x0b\x32\x06.Color\x12!\n\x08material\x18\x06 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x18\n\x05slots\x18\x08 \x03(\x0b\x32\t.GearSlot\"@\n\x05\x43olor\x12\x0b\n\x03red\x18\x01 \x01(\x05\x12\r\n\x05green\x18\x02 \x01(\x05\x12\x0c\n\x04\x62lue\x18\x03 \x01(\x05\x12\r\n\x05\x61lpha\x18\x04 \x01(\x05\"T\n\x08GearSlot\x12\x1d\n\x04slot\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12)\n\x10gear_progression\x18\x02 \x01(\x0b\x32\x0f.ObjectIdentityb\x06proto3')



_GEARSETS = DESCRIPTOR.message_types_by_name['GearSets']
_GEARSET = DESCRIPTOR.message_types_by_name['GearSet']
_GEARSETINFO = DESCRIPTOR.message_types_by_name['GearSetInfo']
_COLOR = DESCRIPTOR.message_types_by_name['Color']
_GEARSLOT = DESCRIPTOR.message_types_by_name['GearSlot']
GearSets = _reflection.GeneratedProtocolMessageType('GearSets', (_message.Message,), {
  'DESCRIPTOR' : _GEARSETS,
  '__module__' : 'files.gear_sets.gear_sets_pb2'
  # @@protoc_insertion_point(class_scope:GearSets)
  })
_sym_db.RegisterMessage(GearSets)

GearSet = _reflection.GeneratedProtocolMessageType('GearSet', (_message.Message,), {
  'DESCRIPTOR' : _GEARSET,
  '__module__' : 'files.gear_sets.gear_sets_pb2'
  # @@protoc_insertion_point(class_scope:GearSet)
  })
_sym_db.RegisterMessage(GearSet)

GearSetInfo = _reflection.GeneratedProtocolMessageType('GearSetInfo', (_message.Message,), {
  'DESCRIPTOR' : _GEARSETINFO,
  '__module__' : 'files.gear_sets.gear_sets_pb2'
  # @@protoc_insertion_point(class_scope:GearSetInfo)
  })
_sym_db.RegisterMessage(GearSetInfo)

Color = _reflection.GeneratedProtocolMessageType('Color', (_message.Message,), {
  'DESCRIPTOR' : _COLOR,
  '__module__' : 'files.gear_sets.gear_sets_pb2'
  # @@protoc_insertion_point(class_scope:Color)
  })
_sym_db.RegisterMessage(Color)

GearSlot = _reflection.GeneratedProtocolMessageType('GearSlot', (_message.Message,), {
  'DESCRIPTOR' : _GEARSLOT,
  '__module__' : 'files.gear_sets.gear_sets_pb2'
  # @@protoc_insertion_point(class_scope:GearSlot)
  })
_sym_db.RegisterMessage(GearSlot)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEARSETS._serialized_start=62
  _GEARSETS._serialized_end=101
  _GEARSET._serialized_start=103
  _GEARSET._serialized_end=175
  _GEARSETINFO._serialized_start=178
  _GEARSETINFO._serialized_end=367
  _COLOR._serialized_start=369
  _COLOR._serialized_end=433
  _GEARSLOT._serialized_start=435
  _GEARSLOT._serialized_end=519
# @@protoc_insertion_point(module_scope)
