# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/progressions/progressions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%files/progressions/progressions.proto\x1a\x19\x66iles/common/common.proto\"\xfd\x02\n\x0cProgressions\x12/\n\x0cprogressions\x18\x01 \x03(\x0b\x32\x19.Progressions.Progression\x1a\x46\n\x0bProgression\x12\n\n\x02id\x18\x01 \x01(\x06\x12+\n\x04info\x18\x02 \x01(\x0b\x32\x1d.Progressions.ProgressionInfo\x1aq\n\x0fProgressionInfo\x12+\n\nint_values\x18\x01 \x01(\x0b\x32\x17.Progressions.IntValues\x12\x31\n\rdouble_values\x18\x02 \x01(\x0b\x32\x1a.Progressions.DoubleValues\x1a>\n\tIntValues\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x0e\n\x06values\x18\x02 \x03(\x03\x1a\x41\n\x0c\x44oubleValues\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x0e\n\x06values\x18\x02 \x03(\x01\x62\x06proto3')



_PROGRESSIONS = DESCRIPTOR.message_types_by_name['Progressions']
_PROGRESSIONS_PROGRESSION = _PROGRESSIONS.nested_types_by_name['Progression']
_PROGRESSIONS_PROGRESSIONINFO = _PROGRESSIONS.nested_types_by_name['ProgressionInfo']
_PROGRESSIONS_INTVALUES = _PROGRESSIONS.nested_types_by_name['IntValues']
_PROGRESSIONS_DOUBLEVALUES = _PROGRESSIONS.nested_types_by_name['DoubleValues']
Progressions = _reflection.GeneratedProtocolMessageType('Progressions', (_message.Message,), {

  'Progression' : _reflection.GeneratedProtocolMessageType('Progression', (_message.Message,), {
    'DESCRIPTOR' : _PROGRESSIONS_PROGRESSION,
    '__module__' : 'files.progressions.progressions_pb2'
    # @@protoc_insertion_point(class_scope:Progressions.Progression)
    })
  ,

  'ProgressionInfo' : _reflection.GeneratedProtocolMessageType('ProgressionInfo', (_message.Message,), {
    'DESCRIPTOR' : _PROGRESSIONS_PROGRESSIONINFO,
    '__module__' : 'files.progressions.progressions_pb2'
    # @@protoc_insertion_point(class_scope:Progressions.ProgressionInfo)
    })
  ,

  'IntValues' : _reflection.GeneratedProtocolMessageType('IntValues', (_message.Message,), {
    'DESCRIPTOR' : _PROGRESSIONS_INTVALUES,
    '__module__' : 'files.progressions.progressions_pb2'
    # @@protoc_insertion_point(class_scope:Progressions.IntValues)
    })
  ,

  'DoubleValues' : _reflection.GeneratedProtocolMessageType('DoubleValues', (_message.Message,), {
    'DESCRIPTOR' : _PROGRESSIONS_DOUBLEVALUES,
    '__module__' : 'files.progressions.progressions_pb2'
    # @@protoc_insertion_point(class_scope:Progressions.DoubleValues)
    })
  ,
  'DESCRIPTOR' : _PROGRESSIONS,
  '__module__' : 'files.progressions.progressions_pb2'
  # @@protoc_insertion_point(class_scope:Progressions)
  })
_sym_db.RegisterMessage(Progressions)
_sym_db.RegisterMessage(Progressions.Progression)
_sym_db.RegisterMessage(Progressions.ProgressionInfo)
_sym_db.RegisterMessage(Progressions.IntValues)
_sym_db.RegisterMessage(Progressions.DoubleValues)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROGRESSIONS._serialized_start=69
  _PROGRESSIONS._serialized_end=450
  _PROGRESSIONS_PROGRESSION._serialized_start=134
  _PROGRESSIONS_PROGRESSION._serialized_end=204
  _PROGRESSIONS_PROGRESSIONINFO._serialized_start=206
  _PROGRESSIONS_PROGRESSIONINFO._serialized_end=319
  _PROGRESSIONS_INTVALUES._serialized_start=321
  _PROGRESSIONS_INTVALUES._serialized_end=383
  _PROGRESSIONS_DOUBLEVALUES._serialized_start=385
  _PROGRESSIONS_DOUBLEVALUES._serialized_end=450
# @@protoc_insertion_point(module_scope)
