# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/gear_set_progressions/gear_set_progressions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7files/gear_set_progressions/gear_set_progressions.proto\x1a\x19\x66iles/common/common.proto\"I\n\x13GearSetProgressions\x12\x32\n\x15gear_set_progressions\x18\x01 \x03(\x0b\x32\x13.GearSetProgression\"@\n\x12GearSetProgression\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x1e\n\x04info\x18\x02 \x01(\x0b\x32\x10.ProgressionInfo\"\x87\x01\n\x0fProgressionInfo\x12\x33\n\tequipment\x18\x01 \x01(\x0b\x32\x1e.EquipmentLevelProgressionInfoH\x00\x12+\n\x08gear_set\x18\x03 \x01(\x0b\x32\x17.GearSetProgressionInfoH\x00\x42\x12\n\x10progression_info\"\x1f\n\x1d\x45quipmentLevelProgressionInfo\"Z\n\x16GearSetProgressionInfo\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12\x1d\n\x15gear_names_with_level\x18\x02 \x03(\tb\x06proto3')



_GEARSETPROGRESSIONS = DESCRIPTOR.message_types_by_name['GearSetProgressions']
_GEARSETPROGRESSION = DESCRIPTOR.message_types_by_name['GearSetProgression']
_PROGRESSIONINFO = DESCRIPTOR.message_types_by_name['ProgressionInfo']
_EQUIPMENTLEVELPROGRESSIONINFO = DESCRIPTOR.message_types_by_name['EquipmentLevelProgressionInfo']
_GEARSETPROGRESSIONINFO = DESCRIPTOR.message_types_by_name['GearSetProgressionInfo']
GearSetProgressions = _reflection.GeneratedProtocolMessageType('GearSetProgressions', (_message.Message,), {
  'DESCRIPTOR' : _GEARSETPROGRESSIONS,
  '__module__' : 'files.gear_set_progressions.gear_set_progressions_pb2'
  # @@protoc_insertion_point(class_scope:GearSetProgressions)
  })
_sym_db.RegisterMessage(GearSetProgressions)

GearSetProgression = _reflection.GeneratedProtocolMessageType('GearSetProgression', (_message.Message,), {
  'DESCRIPTOR' : _GEARSETPROGRESSION,
  '__module__' : 'files.gear_set_progressions.gear_set_progressions_pb2'
  # @@protoc_insertion_point(class_scope:GearSetProgression)
  })
_sym_db.RegisterMessage(GearSetProgression)

ProgressionInfo = _reflection.GeneratedProtocolMessageType('ProgressionInfo', (_message.Message,), {
  'DESCRIPTOR' : _PROGRESSIONINFO,
  '__module__' : 'files.gear_set_progressions.gear_set_progressions_pb2'
  # @@protoc_insertion_point(class_scope:ProgressionInfo)
  })
_sym_db.RegisterMessage(ProgressionInfo)

EquipmentLevelProgressionInfo = _reflection.GeneratedProtocolMessageType('EquipmentLevelProgressionInfo', (_message.Message,), {
  'DESCRIPTOR' : _EQUIPMENTLEVELPROGRESSIONINFO,
  '__module__' : 'files.gear_set_progressions.gear_set_progressions_pb2'
  # @@protoc_insertion_point(class_scope:EquipmentLevelProgressionInfo)
  })
_sym_db.RegisterMessage(EquipmentLevelProgressionInfo)

GearSetProgressionInfo = _reflection.GeneratedProtocolMessageType('GearSetProgressionInfo', (_message.Message,), {
  'DESCRIPTOR' : _GEARSETPROGRESSIONINFO,
  '__module__' : 'files.gear_set_progressions.gear_set_progressions_pb2'
  # @@protoc_insertion_point(class_scope:GearSetProgressionInfo)
  })
_sym_db.RegisterMessage(GearSetProgressionInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEARSETPROGRESSIONS._serialized_start=86
  _GEARSETPROGRESSIONS._serialized_end=159
  _GEARSETPROGRESSION._serialized_start=161
  _GEARSETPROGRESSION._serialized_end=225
  _PROGRESSIONINFO._serialized_start=228
  _PROGRESSIONINFO._serialized_end=363
  _EQUIPMENTLEVELPROGRESSIONINFO._serialized_start=365
  _EQUIPMENTLEVELPROGRESSIONINFO._serialized_end=396
  _GEARSETPROGRESSIONINFO._serialized_start=398
  _GEARSETPROGRESSIONINFO._serialized_end=488
# @@protoc_insertion_point(module_scope)
