# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/common/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66iles/common/common.proto\"*\n\x0eObjectIdentity\x12\n\n\x02id\x18\x01 \x01(\x06\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')



_OBJECTIDENTITY = DESCRIPTOR.message_types_by_name['ObjectIdentity']
ObjectIdentity = _reflection.GeneratedProtocolMessageType('ObjectIdentity', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTIDENTITY,
  '__module__' : 'files.common.common_pb2'
  # @@protoc_insertion_point(class_scope:ObjectIdentity)
  })
_sym_db.RegisterMessage(ObjectIdentity)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECTIDENTITY._serialized_start=29
  _OBJECTIDENTITY._serialized_end=71
# @@protoc_insertion_point(module_scope)
