# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/stat_sets/stat_sets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from files.common import common_pb2 as files_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x66iles/stat_sets/stat_sets.proto\x1a\x19\x66iles/common/common.proto\"\x92\x02\n\x08StatSets\x12$\n\tstat_sets\x18\x01 \x03(\x0b\x32\x11.StatSets.StatSet\x1a\xdf\x01\n\x07StatSet\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12-\n\tstat_list\x18\x02 \x01(\x0b\x32\x1a.StatSets.StatSet.StatList\x1a\x31\n\x08StatList\x12%\n\x05stats\x18\x01 \x03(\x0b\x32\x16.StatSets.StatSet.Stat\x1aO\n\x04Stat\x12!\n\x08identity\x18\x01 \x01(\x0b\x32\x0f.ObjectIdentity\x12$\n\x0bprogression\x18\x02 \x01(\x0b\x32\x0f.ObjectIdentityb\x06proto3')



_STATSETS = DESCRIPTOR.message_types_by_name['StatSets']
_STATSETS_STATSET = _STATSETS.nested_types_by_name['StatSet']
_STATSETS_STATSET_STATLIST = _STATSETS_STATSET.nested_types_by_name['StatList']
_STATSETS_STATSET_STAT = _STATSETS_STATSET.nested_types_by_name['Stat']
StatSets = _reflection.GeneratedProtocolMessageType('StatSets', (_message.Message,), {

  'StatSet' : _reflection.GeneratedProtocolMessageType('StatSet', (_message.Message,), {

    'StatList' : _reflection.GeneratedProtocolMessageType('StatList', (_message.Message,), {
      'DESCRIPTOR' : _STATSETS_STATSET_STATLIST,
      '__module__' : 'files.stat_sets.stat_sets_pb2'
      # @@protoc_insertion_point(class_scope:StatSets.StatSet.StatList)
      })
    ,

    'Stat' : _reflection.GeneratedProtocolMessageType('Stat', (_message.Message,), {
      'DESCRIPTOR' : _STATSETS_STATSET_STAT,
      '__module__' : 'files.stat_sets.stat_sets_pb2'
      # @@protoc_insertion_point(class_scope:StatSets.StatSet.Stat)
      })
    ,
    'DESCRIPTOR' : _STATSETS_STATSET,
    '__module__' : 'files.stat_sets.stat_sets_pb2'
    # @@protoc_insertion_point(class_scope:StatSets.StatSet)
    })
  ,
  'DESCRIPTOR' : _STATSETS,
  '__module__' : 'files.stat_sets.stat_sets_pb2'
  # @@protoc_insertion_point(class_scope:StatSets)
  })
_sym_db.RegisterMessage(StatSets)
_sym_db.RegisterMessage(StatSets.StatSet)
_sym_db.RegisterMessage(StatSets.StatSet.StatList)
_sym_db.RegisterMessage(StatSets.StatSet.Stat)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATSETS._serialized_start=63
  _STATSETS._serialized_end=337
  _STATSETS_STATSET._serialized_start=114
  _STATSETS_STATSET._serialized_end=337
  _STATSETS_STATSET_STATLIST._serialized_start=207
  _STATSETS_STATSET_STATLIST._serialized_end=256
  _STATSETS_STATSET_STAT._serialized_start=258
  _STATSETS_STATSET_STAT._serialized_end=337
# @@protoc_insertion_point(module_scope)
